// ═══════════════════════════════════════════════════════════
// AERCHAIN DOCUMENT TEMPLATE
// Static HTML template builder. Takes structured JSON content
// and renders a complete, self-contained themed HTML document.
// Claude only needs to return the structured JSON — this file
// handles ALL styling, theming, and layout.
// ═══════════════════════════════════════════════════════════

/**
 * Build a complete Aerchain-themed HTML document from structured content.
 * @param {Object} data - Structured content from Claude
 * @param {string} data.title - Document title
 * @param {string} [data.subtitle] - Optional subtitle
 * @param {Array} data.sections - Array of section objects
 * @param {string} theme - Theme ID (e.g. "purple-glass")
 * @returns {string} Complete HTML document string
 */
export function buildThemedDocument(data, theme = "purple-glass") {
  if (!data || !data.sections) return "";
  const sectionsHTML = data.sections.map(renderSection).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(data.title || "Aerchain Document")}</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
${TEMPLATE_CSS}
</style>
</head>
<body data-theme="${esc(theme)}">

<nav>
  <div class="logo"><span>Aer</span>Chain</div>
  <div class="theme-bar">
    <span class="tb-label">Theme</span>
    <div class="td active" data-t="purple-glass" style="background:#7c3aed" onclick="st(this)"></div>
    <div class="td" data-t="deep-ocean" style="background:#0ea5e9" onclick="st(this)"></div>
    <div class="td" data-t="rose-quartz" style="background:#ec4899" onclick="st(this)"></div>
    <div class="td" data-t="midnight-emerald" style="background:#10b981" onclick="st(this)"></div>
    <div class="td" data-t="arctic" style="background:#3b82f6" onclick="st(this)"></div>
    <div class="td" data-t="topaz" style="background:#14b8a6" onclick="st(this)"></div>
    <div class="td" data-t="citrine" style="background:#eab308" onclick="st(this)"></div>
    <div class="td" data-t="slate" style="background:#6366f1" onclick="st(this)"></div>
  </div>
</nav>

<main>
  <section class="hero">
    <div class="eyebrow">AERCHAIN DOCUMENT</div>
    <h1>${formatHeading(data.title || "Untitled")}</h1>
    ${data.subtitle ? `<p class="subtitle">${esc(data.subtitle)}</p>` : ""}
  </section>

  ${sectionsHTML}
</main>

<footer>
  <div class="footer-inner">
    <div class="footer-logo"><span>Aer</span>Chain</div>
    <div class="footer-note">Generated by Aerchain SalesOS Document Formatter</div>
  </div>
</footer>

<script>
function st(el){document.body.setAttribute('data-theme',el.dataset.t);document.querySelectorAll('.td').forEach(d=>d.classList.remove('active'));el.classList.add('active')}
</script>
</body>
</html>`;
}

// ── Section renderers ──────────────────────────────────────

function renderSection(s) {
  switch (s.type) {
    case "text": return renderText(s);
    case "kpis": return renderKPIs(s);
    case "cards": return renderCards(s);
    case "table": return renderTable(s);
    case "list": return renderList(s);
    case "quote": return renderQuote(s);
    case "divider": return `<div class="divider"></div>`;
    case "image-note": return renderImageNote(s);
    default: return renderText(s); // fallback
  }
}

function sectionHeader(s) {
  let html = "";
  if (s.eyebrow) html += `<div class="eyebrow">${esc(s.eyebrow)}</div>`;
  if (s.heading) html += `<h2>${formatHeading(s.heading)}</h2>`;
  return html;
}

function renderText(s) {
  const paragraphs = (s.content || "")
    .split(/\n\n+/)
    .filter(Boolean)
    .map(p => `<p>${esc(p)}</p>`)
    .join("\n    ");
  return `
  <section class="content-section">
    ${sectionHeader(s)}
    ${paragraphs}
  </section>`;
}

function renderKPIs(s) {
  if (!s.items || !s.items.length) return "";
  const cards = s.items.map(k => `
      <div class="kpi-card">
        <div class="kpi-value">${esc(k.value)}</div>
        <div class="kpi-label">${esc(k.label)}</div>
      </div>`).join("");
  return `
  <section class="content-section">
    ${sectionHeader(s)}
    <div class="kpi-grid">${cards}
    </div>
  </section>`;
}

function renderCards(s) {
  if (!s.items || !s.items.length) return "";
  const cards = s.items.map(c => `
      <div class="glass-card">
        <div class="card-title">${esc(c.title)}</div>
        <div class="card-desc">${esc(c.description || "")}</div>
      </div>`).join("");
  return `
  <section class="content-section">
    ${sectionHeader(s)}
    <div class="card-grid">${cards}
    </div>
  </section>`;
}

function renderTable(s) {
  if (!s.headers || !s.rows) return "";
  const ths = s.headers.map(h => `<th>${esc(h)}</th>`).join("");
  const trs = s.rows.map(row => {
    const tds = row.map(cell => `<td>${esc(String(cell))}</td>`).join("");
    return `<tr>${tds}</tr>`;
  }).join("\n        ");
  return `
  <section class="content-section">
    ${sectionHeader(s)}
    <div class="table-wrap">
      <table>
        <thead><tr>${ths}</tr></thead>
        <tbody>
        ${trs}
        </tbody>
      </table>
    </div>
  </section>`;
}

function renderList(s) {
  if (!s.items || !s.items.length) return "";
  const tag = s.ordered ? "ol" : "ul";
  const lis = s.items.map(i => `<li>${esc(i)}</li>`).join("\n      ");
  return `
  <section class="content-section">
    ${sectionHeader(s)}
    <${tag} class="styled-list">
      ${lis}
    </${tag}>
  </section>`;
}

function renderQuote(s) {
  return `
  <section class="content-section">
    <blockquote class="glass-quote">
      <p>${esc(s.text)}</p>
      ${s.attribution ? `<cite>${esc(s.attribution)}</cite>` : ""}
    </blockquote>
  </section>`;
}

function renderImageNote(s) {
  return `
  <section class="content-section">
    ${sectionHeader(s)}
    <div class="image-note">
      <div class="image-note-icon">&#128444;</div>
      <p>${esc(s.description || "Visual element from source document")}</p>
    </div>
  </section>`;
}

// ── Helpers ─────────────────────────────────────────────────

function esc(str) {
  if (!str) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Apply gradient bold to words wrapped in **word** markdown syntax */
function formatHeading(text) {
  return esc(text).replace(/\*\*(.+?)\*\*/g, '<b class="gradient-text">$1</b>');
}

// ── Static CSS ──────────────────────────────────────────────

const TEMPLATE_CSS = `
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --canvas-a:hsl(262 55% 18%);--canvas-b:hsl(270 45% 12%);--canvas-c:hsl(255 40% 10%);--canvas-d:hsl(245 35% 8%);
  --aerchain:#DC5F40;
  --gp:linear-gradient(135deg,hsl(262 80% 55%),hsl(275 85% 58%));
  --active-glow:hsl(262 80% 55%/.25);
  --col-purple:hsl(262 80% 55%);--col-blue:hsl(217 88% 58%);--col-green:hsl(152 68% 42%);
  --col-amber:hsl(38 92% 50%);--col-red:hsl(0 68% 48%);--col-orange:hsl(18 90% 55%);
  --glass-1:rgba(255,255,255,.03);--glass-2:rgba(255,255,255,.06);--glass-3:rgba(255,255,255,.10);
  --glass-border:rgba(255,255,255,.06);--glass-border-h:rgba(255,255,255,.14);
  --fg:rgba(255,255,255,.94);--fg2:rgba(255,255,255,.72);--fg3:rgba(255,255,255,.42);
  --nav-bg:linear-gradient(180deg,hsl(262 40% 14%/.96),hsl(255 35% 10%/.88));
  --dot:radial-gradient(rgba(255,255,255,.045) 1px,transparent 1px);
  --r:16px;--rm:12px;
}

/* Theme variants */
[data-theme="deep-ocean"]{--canvas-a:hsl(200 55% 16%);--canvas-b:hsl(210 50% 11%);--canvas-c:hsl(215 45% 9%);--canvas-d:hsl(220 40% 7%);--gp:linear-gradient(135deg,hsl(195 85% 45%),hsl(175 80% 42%));--active-glow:hsl(195 85% 45%/.25);--nav-bg:linear-gradient(180deg,hsl(200 55% 16%/.96),hsl(210 50% 11%/.88))}
[data-theme="rose-quartz"]{--canvas-a:hsl(330 38% 15%);--canvas-b:hsl(335 32% 11%);--canvas-c:hsl(340 28% 9%);--canvas-d:hsl(345 22% 7%);--gp:linear-gradient(135deg,hsl(330 72% 58%),hsl(290 70% 55%));--active-glow:hsl(330 72% 58%/.25);--nav-bg:linear-gradient(180deg,hsl(330 30% 13%/.96),hsl(335 25% 9%/.88))}
[data-theme="midnight-emerald"]{--canvas-a:hsl(155 40% 14%);--canvas-b:hsl(160 35% 10%);--canvas-c:hsl(165 30% 8%);--canvas-d:hsl(170 25% 6%);--gp:linear-gradient(135deg,hsl(152 68% 42%),hsl(165 75% 38%));--active-glow:hsl(152 68% 42%/.25);--nav-bg:linear-gradient(180deg,hsl(155 35% 12%/.96),hsl(160 30% 8%/.88))}
[data-theme="arctic"]{--canvas-a:hsl(225 45% 16%);--canvas-b:hsl(230 40% 12%);--canvas-c:hsl(235 35% 9%);--canvas-d:hsl(240 30% 7%);--gp:linear-gradient(135deg,hsl(217 88% 58%),hsl(200 90% 55%));--active-glow:hsl(217 88% 58%/.25);--nav-bg:linear-gradient(180deg,hsl(225 40% 14%/.96),hsl(230 35% 10%/.88))}
[data-theme="topaz"]{--canvas-a:hsl(192 40% 14%);--canvas-b:hsl(196 36% 10%);--canvas-c:hsl(200 32% 8%);--canvas-d:hsl(205 28% 6%);--gp:linear-gradient(135deg,hsl(188 80% 48%),hsl(42 88% 52%));--active-glow:hsl(188 80% 48%/.25);--nav-bg:linear-gradient(180deg,hsl(192 35% 12%/.96),hsl(196 30% 8%/.88))}
[data-theme="citrine"]{--canvas-a:hsl(48 55% 12%);--canvas-b:hsl(45 50% 9%);--canvas-c:hsl(42 45% 7%);--canvas-d:hsl(38 40% 5%);--gp:linear-gradient(135deg,hsl(48 95% 52%),hsl(38 90% 44%));--active-glow:hsl(48 95% 52%/.30);--nav-bg:linear-gradient(180deg,hsl(48 45% 10%/.96),hsl(45 40% 7%/.88))}
[data-theme="slate"]{--canvas-a:hsl(215 22% 15%);--canvas-b:hsl(218 20% 11%);--canvas-c:hsl(220 18% 9%);--canvas-d:hsl(222 16% 7%);--gp:linear-gradient(135deg,hsl(213 72% 52%),hsl(232 68% 58%));--active-glow:hsl(213 72% 52%/.25);--nav-bg:linear-gradient(180deg,hsl(215 20% 13%/.96),hsl(218 18% 9%/.88))}

html,body{height:100%;font-family:'Montserrat',system-ui,sans-serif;color:var(--fg);
  background:linear-gradient(145deg,var(--canvas-d),var(--canvas-c) 30%,var(--canvas-b) 60%,var(--canvas-a) 100%) fixed}

/* Nav */
nav{position:sticky;top:0;z-index:50;display:flex;align-items:center;justify-content:space-between;
  padding:0 32px;height:56px;background:var(--nav-bg);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px);
  border-bottom:1px solid var(--glass-border)}
.logo{font-weight:700;font-size:18px;letter-spacing:-.02em}
.logo span{color:var(--aerchain)}
.theme-bar{display:flex;align-items:center;gap:6px}
.tb-label{font-family:'JetBrains Mono',monospace;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.12em;color:var(--fg3);margin-right:4px}
.td{width:12px;height:12px;border-radius:50%;cursor:pointer;border:2px solid transparent;transition:border-color .2s,transform .2s}
.td:hover{transform:scale(1.2)}
.td.active{border-color:rgba(255,255,255,.7)}

/* Main */
main{max-width:1280px;margin:0 auto;padding:80px 48px}

/* Hero */
.hero{margin-bottom:64px}
.hero h1{font-size:clamp(36px,5vw,64px);font-weight:300;letter-spacing:-.03em;line-height:1.1;margin-top:12px}
.subtitle{font-size:18px;color:var(--fg2);margin-top:16px;font-weight:400;max-width:680px;line-height:1.6}

/* Eyebrow */
.eyebrow{font-family:'JetBrains Mono',monospace;font-size:11px;font-weight:700;text-transform:uppercase;
  letter-spacing:.14em;color:var(--fg3);display:flex;align-items:center;gap:8px;margin-bottom:8px}
.eyebrow::before{content:'';width:16px;height:1.5px;border-radius:1px;background:var(--gp)}

/* Gradient text */
.gradient-text{background:var(--gp);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;font-weight:700}

/* Content sections */
.content-section{margin-bottom:56px}
.content-section h2{font-size:clamp(24px,3vw,40px);font-weight:300;letter-spacing:-.025em;line-height:1.2;margin-bottom:20px}
.content-section p{font-size:15px;color:var(--fg2);line-height:1.7;margin-bottom:12px;max-width:780px}

/* KPI grid */
.kpi-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin-top:20px}
.kpi-card{background:var(--glass-1);border:1px solid var(--glass-border);border-radius:var(--r);padding:24px;
  text-align:center;transition:all .3s}
.kpi-card:hover{border-color:var(--glass-border-h);transform:translateY(-3px);box-shadow:0 14px 44px rgba(0,0,0,.22)}
.kpi-value{font-size:36px;font-weight:700;background:var(--gp);-webkit-background-clip:text;
  -webkit-text-fill-color:transparent;background-clip:text;margin-bottom:8px}
.kpi-label{font-family:'JetBrains Mono',monospace;font-size:11px;font-weight:600;text-transform:uppercase;
  letter-spacing:.1em;color:var(--fg3)}

/* Card grid */
.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px;margin-top:20px}
.glass-card{background:var(--glass-1);border:1px solid var(--glass-border);border-radius:var(--r);padding:24px;
  transition:all .3s;position:relative;overflow:hidden}
.glass-card::before{content:'';position:absolute;inset:0;background:var(--dot);background-size:24px 24px;opacity:.5;pointer-events:none}
.glass-card:hover{border-color:var(--glass-border-h);transform:translateY(-3px);box-shadow:0 14px 44px rgba(0,0,0,.22)}
.card-title{font-size:16px;font-weight:600;margin-bottom:8px;color:var(--fg)}
.card-desc{font-size:13px;color:var(--fg2);line-height:1.6}

/* Table */
.table-wrap{overflow-x:auto;margin-top:16px}
table{width:100%;border-collapse:collapse;background:var(--glass-1);border:1px solid var(--glass-border);border-radius:var(--rm);overflow:hidden}
thead{background:var(--glass-2)}
th{font-family:'JetBrains Mono',monospace;font-size:11px;font-weight:700;text-transform:uppercase;
  letter-spacing:.08em;color:var(--fg3);padding:12px 16px;text-align:left;border-bottom:1px solid var(--glass-border)}
td{padding:12px 16px;font-size:14px;color:var(--fg2);border-bottom:1px solid var(--glass-border)}
tr:last-child td{border-bottom:none}
tr:hover td{background:var(--glass-2)}

/* Lists */
.styled-list{list-style:none;padding:0;margin-top:12px}
.styled-list li{position:relative;padding:8px 0 8px 24px;font-size:15px;color:var(--fg2);line-height:1.6}
.styled-list li::before{content:'';position:absolute;left:0;top:16px;width:8px;height:8px;border-radius:50%;background:var(--gp)}
ol.styled-list{counter-reset:item}
ol.styled-list li{counter-increment:item}
ol.styled-list li::before{content:counter(item);width:20px;height:20px;border-radius:50%;background:var(--gp);
  display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700;color:#fff;top:10px}

/* Quotes */
.glass-quote{background:var(--glass-1);border:1px solid var(--glass-border);border-left:3px solid;
  border-image:var(--gp) 1;border-radius:0 var(--rm) var(--rm) 0;padding:24px 28px;margin:20px 0;
  backdrop-filter:blur(12px)}
.glass-quote p{font-size:16px;font-style:italic;color:var(--fg);line-height:1.7;margin:0}
.glass-quote cite{display:block;margin-top:12px;font-size:13px;color:var(--fg3);font-style:normal;
  font-family:'JetBrains Mono',monospace}

/* Image note */
.image-note{background:var(--glass-1);border:1px solid var(--glass-border);border-radius:var(--r);
  padding:24px;display:flex;align-items:flex-start;gap:16px}
.image-note-icon{font-size:28px;opacity:.5}
.image-note p{font-size:13px;color:var(--fg2);line-height:1.6;margin:0;font-style:italic}

/* Divider */
.divider{height:1px;background:linear-gradient(90deg,var(--glass-border),transparent);margin:40px 0}

/* Footer */
footer{border-top:1px solid var(--glass-border);padding:40px 48px;margin-top:40px}
.footer-inner{max-width:1280px;margin:0 auto;display:flex;align-items:center;justify-content:space-between}
.footer-logo{font-weight:700;font-size:14px;letter-spacing:-.02em}
.footer-logo span{color:var(--aerchain)}
.footer-note{font-family:'JetBrains Mono',monospace;font-size:10px;color:var(--fg3);text-transform:uppercase;letter-spacing:.1em}

/* Responsive */
@media(max-width:768px){
  main{padding:40px 20px}
  .hero h1{font-size:32px}
  .kpi-grid,.card-grid{grid-template-columns:1fr}
  nav{padding:0 16px}
}

/* Scrollbar */
::-webkit-scrollbar{width:6px}
::-webkit-scrollbar-track{background:transparent}
::-webkit-scrollbar-thumb{background:var(--glass-border-h);border-radius:3px}
`;
